### ISSUE TITLE
Mortared block cost

### ISSUE THREAD

**Issue by BeeEnjoyer** [TheSnarkyKnight/SaturaLanx#1]
Hello, not sure if this is the correct place to ask, but I've noticed that mortared cobblestone blocks are extremely expensive material-wise compared to the closest counterpart I could find — bricks. Both require basic metallurgy to be made due to 3x3 grid recipe, but while bricks have 5+4:4 cost/output ratio, mortared cobblestone only has 4+4:1 ratio, making it too costly for anything other than dedicated cosmetic block. I'd like to know is this intentional design or not. Thank you in advance.

**Comment by TheSnarkyKnight** [comment]
Hi, this place is fine for asking questions (though you can also find me on the TFC+ discord).
Mortared cobble is meant to be a dedicated cosmetic block, an alternative to cobble that looks similar but is not affected by gravity (there's also a config option to completely turn off the custom texture, making it look exactly like cobble). 
You make a good point however, as its current recipe is very expensive and will likely be changed in the next update.

**Comment by TheSnarkyKnight** [comment]
The amount of mortared cobblestone made per-craft was increased in version 0.2.3.1
